import 'mood_type.dart';

/// A journal entry (`users/{uid}/journal_entries/{entryId}`).
class JournalEntry {
  const JournalEntry({
    required this.id,
    required this.title,
    required this.content,
    required this.mood,
    required this.tags,
    required this.createdAt,
    required this.updatedAt,
    this.aiInsight,
    this.photoUrl,
  });

  final String id;
  final String title;
  final String content;
  final MoodType? mood;
  final List<String> tags;

  /// Short supportive insight generated by the AI Coach backend on save.
  final String? aiInsight;
  final String? photoUrl;
  final DateTime createdAt;
  final DateTime updatedAt;

  JournalEntry copyWith({String? aiInsight}) => JournalEntry(
        id: id,
        title: title,
        content: content,
        mood: mood,
        tags: tags,
        aiInsight: aiInsight ?? this.aiInsight,
        photoUrl: photoUrl,
        createdAt: createdAt,
        updatedAt: updatedAt,
      );
}
